name: TSC -> 11ty build -> Deploy to GitHub Pages
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install all Node packages
        run: npm ci
      - name: Run tsc using .tsconfig settings
        run: npx tsc
      - name: Confirmation of TSC
        run: |
          node "testing.js"
          echo "If the console.log output is seen then compiliation was successful"
        working-directory: ./src
      - name: WIP - run the 11ty build
        run: echo "Running the 11ty build... (WIP)"
      - name: WIP - deploy to GitHub pages
        run: echo "Deploying to GitHub pages... (WIP)"
