name: TSC -> 11ty build -> Deploy to GitHub Pages
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install all Node packages
        run: npm ci
      - name: Run tsc using .tsconfig settings
        run: npx tsc
      - name: Confirmation of TSC
        run: |
          node "testing.js"
          echo "If the console.log output is seen then compiliation was successful"
        working-directory: ./src/assets/js
      - name: WIP - run the 11ty build
        run: npm run build:prod
      - name: Confirmation of 11ty build
        run: |
          cd "./build"
          ls

      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy
